controller_list:
  - name: fake_arx5_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link_to_link1
      - link1_to_link2
      - link2_to_link3
      - link3_to_link4
      - link4_to_link5
      - link5_to_gripper_link1
initial:  # Define initial robot poses per group
  - group: arx5_arm
    pose: Home